# Generated by Django 4.1 on 2024-03-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="userid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
