# Generated by Django 4.1 on 2024-03-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudApp", "0002_remove_user_id_alter_user_userid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="taskid",
        ),
        migrations.AddField(
            model_name="task",
            name="taskid2",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
