# Generated by Django 4.1 on 2024-03-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudApp", "0003_remove_task_taskid_task_taskid2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="taskid2",
            new_name="taskid",
        ),
    ]
