# Generated by Django 4.1 on 2024-03-13 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crudApp", "0005_rename_userid_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="crudApp.user",
            ),
        ),
    ]
