# Generated by Django 5.0.3 on 2024-03-13 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudApp", "0006_alter_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="access_token",
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 3, 13, 18, 24, 2, 79937, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
