# Generated by Django 5.0.3 on 2024-03-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudApp", "0010_user_groups_user_is_superuser_user_last_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
