# Generated by Django 5.0.3 on 2024-03-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "crudApp",
            "0013_remove_user_access_token_user_created_at_user_groups_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
