# Generated by Django 5.0.3 on 2024-03-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudApp", "0015_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
    ]
