# Generated by Django 5.0.3 on 2024-03-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudApp", "0018_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
