# Generated by Django 5.0.3 on 2024-03-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudApp", "0019_alter_user_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="userid",
            new_name="id",
        ),
    ]
